config/routes.rb
Wec2011Web::Application.routes.draw do
  resources :participants

	match '/', :to => 'pages#home'
	match '/home' => 'pages#home'
	match '/agenda', :to => 'pages#agenda'
	match '/about_us', :to => 'pages#about_us'
	match '/career_support', :to => 'pages#career_support'
	match '/companies', :to => 'pages#companies'
	match '/faq', :to => 'pages#faq'
	match '/gallery', :to => 'pages#gallery'
	match '/location', :to => 'pages#location'
	match '/contact', :to => 'pages#contact'
	match '/competitions', :to => 'pages#competitions'

	scope "/:locale" do
	  resources :participants
	end
	
	match '/:locale' => 'pages#home'

  root :to => 'pages#home'

end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	validates :name, :presence =>  {:message => "is blank!"}
	validates :surname, :presence =>   {:message => "is blank!"}
	validates :email, :presence =>   {:message => "is blank!"}
	validates :studies, :presence =>   {:message => "is blank!"}
	validates :year_of_studies, :presence =>   {:message => "is blank!"}
	validates :terms,  :acceptance => { :accept => 1, :message => "must be accepted!"}
end

	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	before_filter :set_locale

	def default_url_options(options={})
		logger.debug "default_url_options is passed options: #{options.inspect}\n"
  		{ :locale => I18n.locale }
	end
	
	def set_locale
	  	I18n.locale = params[:locale] || I18n.default_locale
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html {redirect_to home_path}
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
      respond_to do |format|
      format.html {redirect_to home_path}  end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    format.html {redirect_to home_path}
  end

  # POST /participants
  # POST /participants.json
  def create

    @participant = Participant.new(params[:participant])

	require 'fileutils'
	@tmp = params[:cv_file]

    respond_to do |format|
      if @participant.save

        # Tell the ParticipantMailer to send an e-mail
        ParticipantMailer.participate_email(@participant, @tmp).deliver

	#format.html {redirect_to home_path}

	format.html { render action: "created" }
        #format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end


  # after a participant is created redirect to "thank you" page
  def created
      respond_to do |format|
      format.html # created.html.erb
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    respond_to do |format|
      format.html {redirect_to home_path}
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    respond_to do |format|
     format.html {redirect_to home_path}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_title(text)
    @title = t(text)
  end
  
  def title
    "- #{@title}"
  end
  
  def set_header(text)
    @header = t(text)
  end
  
  def header
    @header
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag "application" %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script src="/assets/bootstrap-twipsy.js" type="text/javascript"></script>
<script src="/assets/bootstrap-popover.js" type="text/javascript"></script>
<title>BEST Barcelona WEC 2011 <%= title %></title>
<link rel="shortcut icon" href="best_fav.gif"/>
</head>
<body>
	<div class="container">
		<%= image_tag("header.jpg", :alt => "BEST Barcelona WEC 2011") %>

	<div class="container-lang">
	<p>&nbsp;<%= link_to('English', url_for(:locale => 'en'))%>&nbsp; | &nbsp;<%= link_to('Català', url_for(:locale => 'cat'))%>&nbsp; | &nbsp;<%= link_to('Español', url_for(:locale => 'es')) %>&nbsp; | &nbsp;<%= link_to "Contact", contact_path %></p>
	</div>
          	<ul class="pills">
		    <li><%= link_to t(:home), home_path %></li>
		    <li><%= link_to t(:companies), companies_path %></li>
		    <li><%= link_to t(:reg_menu), new_participant_path %></li>
		    <li><%= link_to t(:agenda), agenda_path %></li>
		    <li><%= link_to t(:location), location_path %></li>
		    <li><%= link_to t(:carrer_support), career_support_path %></li>
		    <li><%= link_to t(:competitions), competitions_path %></li>
		    <li><%= link_to t(:gallery), gallery_path %></li>
		    <li><%= link_to t(:about_us), about_us_path %></li>
		    <li><%= link_to t(:faq_menu), faq_path %></li>
          	</ul>
			<div class="container-fluid">
				<div class="sidebar">
      					<a href="http://www.upc.edu/" target="_blank">
					<img src="/sidebar_logos/logoUPC.gif" width="100" height="90"></a>
					<p><a href="http://www.danone.es/" target="_blank"><img src="/sidebar_logos/Danone.gif" width="100" height="70"></p></a>
					<p><a href="http://www.agbar.es/es/home.html" target="_blank"><img src="/sidebar_logos/agbar2.gif", width="100" height="70"></p></a>
					<p><a href="http://www.accenture.com/es-es/Pages/index.aspx" target="_blank"><img src="/sidebar_logos/accenture.gif", width="100" height="70"></p></a>
					<p><a href="http://www.henkel.es/cps/rde/xchg/henkel_ess/hs.xsl/index.htm" target="_blank"><img src="/sidebar_logos/henkel_logo.jpg", width="100" height="70"></p></a>
					<p><a href="http://www.henkelchallenge.com/" target="_blank"><img src="/sidebar_logos/HIC_V_logo.jpg", width="100" height="70"></p></a>
					<p><a href="http://www.tmb.cat" target="_blank"><img src="/sidebar_logos/tmb.jpg", width="100" height="100"></p></a>
					<p><a href="http://www.everis.com/spain/" target="_blank"><img src="/sidebar_logos/logo_everis.jpg", width="110" height="70"></p></a>
					<p><a href="http://ro-botica.com/" target="_blank"><img src="/sidebar_logos/logo_robotica.jpg", width="110" height="70"></p></a>
    				</div>
    				<div class="content">
					<span class="head1"><%= header %></span><br><br>
              				<%= yield %>
    				</div>
  			</div>
	</div>
	<br><br>
	<div class="container-footer">
	<p><b>Copyright &copy; 2011 BEST Barcelona</b></p>
	</div>
</body>
</html>

app/views/pages/about_us.cat.html.erb
<% set_title :about_us %>
<% set_header :about_us %>

<p>
  <a href="http://www.bestbarcelona.org" target="_blank">BEST-UPC</a> és una de les associacions d'estudiants més actives de la UPC. Es va fundar al 1989 i al llarg dels anys ha esdevingut una referència pels estudiants de la UPC que volen ampliar la seva educació tècnica a d'altres països. Cada any centenars d'estudiants de la nostra universitat sol•liciten cursos BEST.
</p>

<p>
  BEST-UPC és un dels 86 grups locals BEST, formant part d'una de les associacions més importants d'Europa. Els seus membres són estudiants de diferents facultats de la UPC que voluntàriament organitzen i coordinen les activitats de l'associació.
</p>

<p>
  El nostre objectiu és proporcionar formació complementària, obrir horitzons i apropar les empreses als estudiants de la UPC. Portem més 20 anys oferint cursos de caràcter tecnològic arreu d'Europa i des de fa 5 anys som pioners en les competicions d'enginyeria que, edició rere edició, aconsegueixen més ressò convertint-se així en un èxit de participació.
</p>

<br><br>
<div class="container-img">
<img src="BEST_UPC.png" width="610" height="350">
</div>

app/views/pages/agenda.es.html.erb
<% set_title :agenda %>
<% set_header :agenda %>

<p>El programa de la BEST-WEC que aparece a continuación puede verse modificado en función de las necesidades.</p><br />

 <ul>
        <li>Workshop Accenture: Lunes 28 Nov de 16 a 19h</li>
        <li>Workshop Danone: Jueves 1 Dic de 11 a 14h</li>
        <li>Workshop Everis: Jueves 1 Dic de 16 a 19h</li>
        <li>Case Study Henkel y Agbar: Martes de 8:30 a 19h</li>
        <li>Case Study TMB: Miércoles de 8:30 a 19h</li>
        <li>Team Design Robótica: Viernes de 8:30 a 14h</li>
</ul>

app/views/pages/career_support.es.html.erb
<% set_title :career_support %>
<% set_header :career_support %>

<p>BEST Career Support es un servicio on-line de BEST que conecta estudiantes e ingenieros con empresas de toda Europa. Es una oportunidad única para iniciar un nuevo y apasionante futuro a la vez que se adquiere experiencia internacional.</p>
<p>BEST Career Support te da la oportunidad de acceder a diversas ofertas de empleo, prácticas y eventos en empresas y universidades, dándote a conocer mediante tu Currículum Vitae.</p>
<p>¡No lo pienses más y <a href="http://www.best.eu.org/student/career">envía tu CV</a>!</p><br />
<div class="container-img">
<%= image_tag("BCS.jpg", :size => "434x327", :alt => "BEST Carrer Support") %>
</div>

app/views/pages/career_support.html.erb
<% set_title :career_support %>
<% set_header :career_support %>

<p>	BEST Career Support is an on-line BEST service which connects students and engineers with the companies of the entire Europe. It is a unique opportunity to open the door for a new and exciting future, gaining international experience at the same time.</p>
<p>BEST Career Support gives you the opportunity to surf among the various offers of companies and universities letting them know you through your curriculum vitae.</p>
<p>Do not hesitate and <a href="http://www.best.eu.org/student/career">send your CV</a>!</p><br />
<div class="container-img">
<%= image_tag("BCS.jpg", :size => "434x327", :alt => "BEST Carrer Support") %>
</div>

app/views/pages/companies.cat.html.erb
<% set_title :companies %>
<% set_header :companies %>


<h3><span class="faq"></span>&nbsp;HENKEL</h3>

<p>El Henkel Innovation Challenge és un business game nacional i internacional que porta celebrant-se 5 anys consecutius. Aquest any, en la seva cinquena edició, participaran 22 països.</p>

<p>El game consisteix en assumir el repte de crear un grup de 2 estudiants i actuar com a directors de desenvolupament de negoci d'un producte existent de  Henkel per l'any 2030.  Els guanyadors de la final internacional gaudiran d'una volta al món i coneixeran personalment al CEO a les oficines centrals de Dusseldorf, Alemanya.</p>

<p>El business game es centra en la innovació i la creativitat. Es centra en les tres línies de negoci de Henkel: Cosmètica/ Cura personal ; Detergents/ Cura de la Llar i Adhesius. Els membres del grup han de presentar una idea innovadora sobre com Henkel pot satisfer les necessitats de la gent al 2030 en temes de cura personal, llar i adhesius.</p>

<p>Durant la BEST Week Engineering Competition 2011 es desenvoluparà  una primera fase d'aquest Henkel Innovation Challenge on durant el dia de la competició els participants hauran de resoldre el business game i presentar-lo a un jurat al final de la jornada. Més tard els participants de la WEC i tothom que hi estigui interessat tindrà  temps per enviar les seves idees fins al 12 de desembre de 2011 per participar en la ronda nacional de la competició.</p>

<p>En les següents fases un grup format per alts directius de Henkel donaran suport i assistència als grups com a mentors, tant a les fases preparatòries per la final nacional com per la final internacional que aquest any es celebrarà  a Berlín, Alemanya.</p>

<br>

<h3><span class="faq"></span>&nbsp;GRUP DANONE</h3> 
<p><b><i>Una companyia global, líder en alimentació i begudes</b></i></p>

<p><b>La nostra missió: proporcionar salut a través de la nutrició al major nombre de persones possibles.</b></p>

<p>Grup Danone és líder als quatre negocis en els quals opera (productes làctics, frescos, aigua envasada, alimentació infantil i nutrició mèdica), gràcies a la qualitat de la seva oferta variada, a les seves fàbriques modernes i als seus anuncis. Però per sobre tot, gràcies al seu equip humà, que treballa dia a dia per a millorar la salut de 300 milions de consumidors arreu del món.</p>

<p>Amb una presència geogràfica a més de 120 països, els 80000 treballadors basem la nostra feina en la qualitat, investigació i la innovació, i, per suposat, mantenint la nostra preocupació pel Medi Ambient i la implicació a les nombroses accions socials, el que ens converteix en una companyia creada per i per a les persones.</p>

<br>

<h3><span class="faq"></span>&nbsp;ACCENTURE</h3> 
<p><b><i>A Accenture apostem per la joventut. Apostem per tu.</b></i></p>

<p>Accenture és una companyia global de consultoria de gestió, serveis tecnològics i outsourcing, amb aproximadament 204.000 persones treballant a més de 120 països. Combinant la seva àmplia experiència, les seves capacitats en tots els sectors i àrees de negoci i la seva extensa investigació, Accenture col·labora amb els seus clients per ajudar-los a convertir les seves organitzacions de negocis i administracions públiques d'alt rendiment.</p>

<p>A Accenture apostem pels joves oferint contracte indefinit des del primer dia. Oferim un ràpid creixement professional, un programa de formació únic, una retribució competitiva i un ampli paquet de beneficis socials en un entorn laboral de col·laboració i amb mesures de flexibilitat i conciliació úniques. A més, formaràs part d'una de les millors empreses per treballar segons Actualitat Econòmica, Merco Persones, CRF o Fortune.</p>

<br>

<h3><span class="faq"></span>&nbsp;AGBAR</h3>

<p>AGBAR és un holding constituït per 168 empreses i 140 anys d’història que opera a àmbits relacionats amb els serveis a la col·lectivitat, principalment en el cicle integral de l’aigua. La nostra missió és la gestió de serveis que contribueixin a la qualitat de la vida de les persones.</p>

<p>L’expansió en l’àmbit internacional, amb presència a Xile, Regne Unit, Xina, Colòmbia, Argèlia, Cuba i Mèxic, consolida el lideratge i el potencial de creixement. Amb una plantilla de 20.360 empleats, Agbar s’ha fixat uns índexs de creixement i de creació de valor continuats que li permeten avançar dia a dia.</p>

<p>Agbar aporta com a filosofia empresarial una decidida aposta per la millora contínua en els seus processos, l'excel·lència en la qualitat, l’aposta per la innovació tecnològica, la capacitat d’adaptació de les noves exigències de la societat i una gestió financera sòlida i eficaç.</p>

<p>En l’àmbit de la Formació i el Desenvolupament, la missió és facilitar la transmissió de coneixements i valors clau dins de l’organització, contribuint a desenvolupar el talent de les persones mitjançant la millora contínua de les seves competències i capacitats, amb la finalitat d’afrontar amb garanties d’èxit els objectius estratègics d’Agbar.</p>

<br>

<h3><span class="faq"></span>&nbsp;everis</h3>

<p><b>everis</b> és una consultora multinacional que ofereix solucions de negoci, estratègia i desenvolupament, manteniment d’aplicacions tecnològiques i outsourcing. La consultora cobreix els sectors de telecomunicacions, entitats financeres, indústria, serveis de computació i energia, banca, assegurances, administracions públiques, mitjans i sanitat. Actualment,everis opera en diversos països d’Europa, Estats Units i Amèrica Llatina i compta amb més de 9.000 professionals.</p>

<p><b>Línies de negoci d’everis</b></p>
<p><b>everis business consulting</b> realitza projectes d’estratègia corporativa, consultoria de negoci i enginyeria de processos. La seva activitat se centra en el coneixement sectorial, en la innovació de serveis i en l’especialització.</p>

<p><b>everis solutions</b> està dedicada a la definició, disseny i implantació de solucions tecnològiques i a la gestió i operació d´outsourcing (aplicacions, infraestructures i processos). Per això, es potencia l’ús de metodologies que asseguren la qualitat, el traspàs de producció als centres d’alt rendiment i l’especialització funcional i tecnològica.</p>

<p><b>everis centers</b> es basa en la utilització de centres d’alt rendiment. Aquesta línia de negoci porta funcionant més de cuatro anys i compta amb l’estructura i les capacitats per realitzar activitats de forma industrialitzada amb un elevat nivell de productivitat i eficiència. Actualment, hi ha centres d’alt rendiment a Sevilla, Múrcia, Alacant, Temuco, San Miguel de Tucumán i Uberlandia.</p>
 
<p><b>everis bpo</b> es focalitza en la prestació de serveis d’externalització de processos de negoci sota acords de nivell de servei, i permet als nostres clients disposar de més capacitat interna per orientar-se a funcions de més valor per al seu negoci i incrementar el control de la qualitat del servei i dels seus costos associats.</p>

<p><b>everis initiatives</b> està atenta a les diferents realitats del mercat per canalitzar i llançar nous negocis en els quals pot invertir amb els seus clients.</p>

<p><b>everis</b> que va iniciar el seu camí a Madrid el 1996, actualment té com a socis inversors el fons d’inversió 3i, el grup Landon i el fons d’inversió britànic Hutton Collins, a més d’un grup minoritari de petits accionistes.</p>

<p>La facturació d’<b>everis</b> per a l’any fiscal 2010 ha estat de 506 milions d’euros.</p>

<p>Avui podem afirmar que el valor diferencial d’<b>everis</b> en el mercat és l’obtenció de resultats, la satisfacció dels nostres clients i la nostra provada experiència en la identificació dels beneficis de negoci.</p>

<br>

<h3><span class="faq"></span>&nbsp;Ro-botica</h3>
<p>La robòtica aviat serà quotidiana a casa nostra. Els canvis que han introduït en les nostres vides el PC o el mòbil són nimis davant la revolució que ens ofereix l'arribada de la robòtica personal i de serveis: els robots ens faran companyia, tindran cura de nosaltres i ens facilitaran la nostra vida quotidiana, suplantant en aquelles tasques més perilloses, delicades, precises, tedioses o repetitives. La robòtica didàctica i educativa és el primer pas d'aquesta revolució que està començant: és la nova eina integral d'aprenentatge.</p>

<p>Des RO-BOTICA volem promoure les vocacions tecnològiques, ja que creiem que en elles es basa el futur del nostre país. Així mateix, volem apropar la robòtica a l'educació, l'oci i les llars.</p>

<p>RO-BOTICA inicia la seva activitat el 2007 a través de la botiga en línia www.ro-botica.com, la primera de l'Estat especialitzada en robòtica educativa i personal. L'any 2008 obre a Barcelona la primera botiga presencial d'Europa dedicada íntegrament a la robòtica educativa i personal.</p>

<p>Actualment RO-BOTICA és distribuïdora oficial o exclusiva de les més avançades plataformes robòtiques escalables i flexibles, de solucions educatives i dels més significatius robots del món.</p>


<br>

<h3><span class="faq"></span>&nbsp;TMB</h3>

<p>Transports Metropolitans de Barcelona és la denominació comuna de les empreses Ferrocarril Metropolità de Barcelona, SA, i Transports de Barcelona, SA, pertanyents a l’Àrea Metropolitana de Barcelona (AMB).</p>

<p>A TMB ens movem cada dia per tu, per acompanyar-te allà on vulguis arribar dins la ciutat de Barcelona i a deu municipis més de l’àrea metropolitana.</p>
 
<p>Com a principal operador de transport públic de Barcelona, i com a part del dia a dia de milers de ciutadans, t’oferim dues xarxes regulars de transport (la de bus —de superfície— i la de metro —subterrània—) i diversos serveis de transport d’oci per:</p>
<ul>
<li>Satisfer les teves necessitats de mobilitat i fer més còmodes i ràpids els teus desplaçaments a la feina, de compres, a casa dels amics...</li>
<li>Oferir un servei públic accessible per a tothom.</li>
<li>Millorar la qualitat de vida a l’àrea metropolitana de Barcelona, retallant les distàncies entre les diferents ciutats i ajudant-te a guanyar temps per a tu i els teus.</li>
</ul>

<p>Et convidem a conèixer millor la nostra companyia!</p>

app/views/pages/contact.cat.html.erb
<% set_title :contact %>
<% set_header :contact %>

<h3>Main Organizers</h3>
<p>iria.perez.rodriguez@best.eu.org</p>
<p>+34 687 31 68 89</p>
<br>
<p>anselmo.ruiz@best.eu.org</p>
<p>+34 685 86 28 78</p>

app/views/pages/home.es.html.erb
<% set_title :home %>
<% set_header :home_header %>

<p>La <b>BEST Week Engineering Competition</b> es una competición de ingeniería a nivel local de una semana de duración. En ella los estudiantes trabajan en equipo usando sus conocimientos técnicos, habilidades sociales y comunicativas para resolver el problema presentado por la empresa en un tiempo determinado.</p>

<p>La BEST-WEC tendrá lugar los días 28, 29 y 30 de noviembre y 1, 2 de diciembre de 2011 en el <%= link_to "Campus Nord de la UPC", location_path %>.</p>

<p>A continuación se detallan las categorías de participación para estudiantes:</p>
<br/>

<span class="label warning">Case Study</span>
<br><br>

<p>En esta categoría se requiere que los participantes den solución a un problema planteado por la empresa participante similar al que puede enfrentarse un ingeniero durante su actividad profesional. Tras un tiempo determinado de trabajo en equipo, las soluciones obtenidas son evaluadas por un jurado compuesto por miembros de la propia empresa así como personal docente universitario.</p>
<br/>

<span class="label warning">Team Design</span>
<br><br>

<p>En esta categoría se busca poner a prueba las habilidades prácticas, creatividad e ingenio de los estudiantes. La empresa participante plantea un problema de manera que cada equipo piense, diseñe y construya la solución que considere más apropiada con el material proporcionado dentro del tiempo establecido. El resultado deberá ser un dispositivo que cumpla los objetivos marcados.</p>
<br/>

<span class="label warning">Workshop</span>
<br><br>

<p>Un Workshop suele consistir en pequeños case studies, simulaciones de negocio, dinámicas de grupo o incluso cursos formativos. Hay un contacto muy próximo entre la empresa y los estudiantes.</p>
<br/>

<span class="label success">¿Cómo puedo participar?</span>
<br><br>

<p>No dejes pasar la experiencia de trabajar con grandes empresas, 
<b>podrás conseguir créditos ALE y un iPod </b>como premio!</p>
<p>Clica <%= link_to "aquí", new_participant_path %> para participar en la BEST-WEC. ¡Es tu oportunidad!</p>

app/views/pages/home.html.erb
<% set_title :home %>
<% set_header :home_header %>

<p><b>BEST Week Engineering Competition</b> is an one-week engineering competition at local level. 
Participants use their technical knowledge and communicative abilities to solve a problem set by a company within a limited time.</p>
<p>BEST-WEC will take place on 28th, 29th and 30th of November and 1st and 2nd of December 2011 in <%= link_to "UPC Campus Nord", location_path %>.</p>
<p>The categories in which students can participate are:</p>
<br/>

<span class="label warning">Case Study</span>
<br><br>

<p>In this category, participants are asked to find a solution to the problem set by the participating company. 
Cases presented are similar to those an engineer can face during his professional career. 
After some team-work time, solutions obtained will be evaluated by a jury consisting of company members and university teaching staff.</p>
<br/>

<span class="label warning">Team Design</span>
<br><br>

<p>In this category, participants are tested on their practical skills, creativity and inventiveness. 
The participating company sets a problem to make each team think, design and construct 
the most appropriate solution using the provided material and within the time limit. 
Result obtained must be a device fulfilling the objectives initially set.</p>
<br/>

<span class="label warning">Workshop</span>
<br><br>

<p>A workshop usually consists of small case studies, business simulations, group dynamics, or even training courses. 
There is a close contact between the companies and students.</p>
<br/>

<span class="label success">How can I participate?</span>
<br><br>

<p>Do not miss the experience to work with remarkable companies, 
<b>you will get ALE credits and an iPod</b> as a prize!</p>
<p>Click <%= link_to "here", new_participant_path %> to participate in BEST-WEC. 
This is your opportunity!</p>

app/views/pages/index.html.erb
<!DOCTYPE html>
<p><b>BEST Week Engineering Competition</b> is an one-week engineering competition at local level. 
Participants use their technical knowledge and communicative abilities to solve a problem set by a company within a limited time.</p>
<p>BEST-WEC will take place on 9th, 10th and 11th of April in <%= link_to "UPC Campus Nord", location_path %> and Barcelona's <a href="http://www.torreagbar.com/home.asp">AGBAR Tower</a>.</p>
<p>The categories in which students can participate are:</p>
<br/>

<span class="label warning">Case Study</span>
<br><br>

<p>In this category, participants are asked to find a solution to the problem set by the participating company. 
Cases presented are similar to those an engineer can face during his professional career. 
After some team-work time, solutions obtained will be evaluated by a jury consisting of company members and university teaching staff.</p>
<br/>

<span class="label warning">Team Design</span>
<br><br>

<p>In this category, participants are tested on their practical skills, creativity and inventiveness. 
The participating company sets a problem to make each team think, design and construct 
the most appropriate solution using the provided material and within the time limit. 
Result obtained must be a device fulfilling the objectives initially set.</p>
<br/>

<span class="label warning">Workshop</span>
<br><br>

<p>A workshop usually consists of small case studies, business simulations, group dynamics, or even training courses. 
There is a close contact between the companies and students.</p>
<br/>

<span class="label success">How can I participate?</span>
<br><br>

<p>Do not miss the experience to work with remarkable companies, 
<b>you will get ALE credits and an iPod</b> as a prize!</p>
<p>Click <%= link_to "here", participants_path %> to participate in BEST-WEC. 
This is your opportunity!</p>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Email</th>
    <th>Studies</th>
    <th>Year of studies</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.name %></td>
    <td><%= participant.surname %></td>
    <td><%= participant.email %></td>
    <td><%= participant.studies %></td>
    <td><%= participant.year_of_studies %></td>
    <td><%= participant.comments %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<% set_title :registration %>
<% set_header :registration %>

<%= render 'form' %>

<!%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @participant.name %>
</p>

<p>
  <b>Surname:</b>
  <%= @participant.surname %>
</p>

<p>
  <b>Email:</b>
  <%= @participant.email %>
</p>

<p>
  <b>Studies:</b>
  <%= @participant.studies %>
</p>

<p>
  <b>Year of studies:</b>
  <%= @participant.year_of_studies %>
</p>

<p>
  <b>Comments:</b>
  <%= @participant.comments %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>